version: "2.0"

services:
  client:
    build: ./docker/node
    ports:
      - 3000:3000
    volumes:
      - ./grpc-client:/usr/src
      - ./proto:/usr/src/proto
    command: ["yarn", "start"]
  server:
    build: ./docker/node
    ports:
      - 3001:3001
    volumes:
      - ./grpc-server:/usr/src
      - ./proto:/usr/src/proto
    command: ["yarn", "start"]
  hybrid:
    build: ./docker/node
    ports:
      - 3002:3002
    volumes:
      - ./grpc-hybrid-server:/usr/src
      - ./proto:/usr/src/proto
    command: ["yarn", "start"]
